name: Labeler
on: [push]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
