name: Greetings

on: [push, pull_request]

env:
  buildDir: ${{ github.workspace }}/build/

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, windows-2019, macos-10.15]
        include:
          - os: ubuntu-18.04
            triplet: x64-linux
          - os: ubuntu-20.04
            triplet: x64-linux
          - os: windows-2019
            triplet: x64-windows
          - os: macos-10.15
            triplet: x64-osx

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
